multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: TwoLinkArm
    base_link: TwoLinkArm_link1
    tip_link: TwoLinkArm_link2
default_collision_operations:
  - object1: base_link
    object2: TwoLinkArm_link1
    operation: disable  # Adjacent in collision
  - object1: TwoLinkArm_link1
    object2: TwoLinkArm_link2
    operation: disable  # Adjacent in collision